language: python
sudo: required
dist: trusty

cache:
  - pip

python:
  - "3.5"

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE="docker-compose -f build/testing.yml"

before_install:
  - apt-cache madison docker-engine
  - "docker version"
  - "docker-compose version"

install:
  - pip install -r ./build/requirements/requirements.txt
  - pip install -r ./build/requirements/requirements_testing.txt

script:
  - echo "Running local tests…" && python manage.py test  # skips integration tests
  - "pep8 ."
  - $DOCKER_COMPOSE build
  - echo "Running complete test suite…" && $DOCKER_COMPOSE run --rm sipa_testing_no_volumes python manage.py test
