name: SIPA CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           submodules: 'true'
      - name: Fix permissions
        run: sudo chmod -R a+rw .
      - name: Build the Docker image
        run: docker build -t sipa:latest .
      - name: Login to GitLab Registry
        uses: docker/login-action@v1 
        with:
          registry: registry.agdsn.de
          username: "github-actions"
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      - name: Tag built image
        run: docker tag sipa:latest registry.agdsn.de/agdsn/coreos/sipa/sipa:${GITHUB_REF##*/}
      - name: Push to GitLab registry
        run: docker push registry.agdsn.de/agdsn/coreos/sipa/sipa:${GITHUB_REF##*/}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           submodules: 'true'
      - name: Fix permissions
        run: sudo chmod -R a+rw .
      - name: Build
        run: docker-compose -f build/testing/docker-compose.yml build
      - name: Start
        run: docker-compose -f build/testing/docker-compose.yml up -d
      - name: Run tests
        run: docker-compose -f build/testing/docker-compose.yml run --rm sipa_testing python manage.py test

